"""
Chainlit版 AI Workspace アプリケーション
動作確認手順
"""

print("=" * 80)
print("✅ Streamlit版を削除完了")
print("=" * 80)
print()
print("🎯 Chainlit版（AI_Workspace_App_Chainlit）のみを使用します")
print()
print("【起動方法】")
print("1. ターミナルを開く")
print("2. cd F:\\10_code\\AI_Workspace_App_Chainlit")
print("3. chainlit run app.py -w")
print()
print("【アクセス】")
print("ブラウザで http://localhost:8000 にアクセス")
print()
print("【ログイン】")
print("ユーザー名: admin")
print("パスワード: admin123")
print()
print("【新機能確認】")
print("1. ログイン後、歯車ボタンをクリック")
print("2. 設定パネルで以下を確認：")
print("   - モデルリスト（APIから動的取得）")
print("   - プロキシ設定（有効/無効トグル、URL入力）")
print()
print("【主な機能】")
print("- OpenAI Responses API with Tools")
print("- Web検索機能")
print("- ファイル検索機能")
print("- ベクトルストア（知識ベース）")
print("- ペルソナ管理")
print("- 履歴管理（SQLite永続化）")
print()
print("=" * 80)
